name: Publish release

on:
  release:
    types:
      - published

jobs:
  ci:
    name: Run CI checks
    permissions:
      id-token: write
      contents: read
      attestations: write
    uses: ./.github/workflows/ci.yml

  publish-to-crates-io:
    name: Publish release to crates.io
    runs-on: ubuntu-latest
    environment: crates.io
    needs: ci
    steps:
      - name: Check out sources
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
